### ISSUE TITLE
Checklist of Implemented Abstract Tests

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-ogcapi-processes10#1]
This GitHub Issue provides a Checklist of implemented Abstract Tests.

**A.2.  Conformance Class Core**

- [x] Abstract Test 1
- [x] Abstract Test 2
- [x] Abstract Test 3
- [x] Abstract Test 4
- [x] Abstract Test 5
- [x] Abstract Test 6
- [x] Abstract Test 7
- [x] Abstract Test 8
- [x] Abstract Test 9
- [x] Abstract Test 10
- [x] Abstract Test 11
- [x] Abstract Test 12
- [x] Abstract Test 13
- [x] Abstract Test 14
- [x] Abstract Test 15
- [x] Abstract Test 16
- [x] Abstract Test 17
- [x] Abstract Test 18
- [x] Abstract Test 19
- [x] Abstract Test 20
- [x] Abstract Test 21
- [x] Abstract Test 22
- [x] Abstract Test 23
- [x] Abstract Test 24
- [x] Abstract Test 25
- [x] Abstract Test 26
- [x] Abstract Test 27
- [x] Abstract Test 28
- [x] Abstract Test 29
- [x] Abstract Test 30
- [x] Abstract Test 31
- [x] Abstract Test 32
- [x] Abstract Test 33
- [x] Abstract Test 34
- [x] Abstract Test 35
- [x] Abstract Test 36
- [x] Abstract Test 37
- [x] Abstract Test 38
- [x] Abstract Test 39
- [x] Abstract Test 40
- [x] Abstract Test 41
- [x] Abstract Test 42
- [x] Abstract Test 43
- [x] Abstract Test 44
- [x] Abstract Test 45
- [x] Abstract Test 46
- [x] Abstract Test 47

**A.3.  Conformance Class OGC Process Description**

- [x] Abstract Test 48
- [x] Abstract Test 49
- [x] Abstract Test 50
- [x] Abstract Test 51
- [x] Abstract Test 52
- [x] Abstract Test 53
- [x] Abstract Test 54

**A.4.  Conformance Class JSON**

- [x] Abstract Test 55

**A.5.  Conformance Class HTML**

- [x] Abstract Test 56
- [x] Abstract Test 57

**A.6.  Conformance Class OpenAPI 3.0**

- [x] Abstract Test 58
- [x] Abstract Test 59
- [x] Abstract Test 60
- [x] Abstract Test 61
- [x] Abstract Test 62
- [x] Abstract Test 63

**A.7.  Conformance Class Job list**

- [x] Abstract Test 64
- [ ] Abstract Test 65
- [ ] Abstract Test 66
- [ ] Abstract Test 67
- [ ] Abstract Test 68
- [ ] Abstract Test 69
- [ ] Abstract Test 70
- [x] Abstract Test 71
- [ ] Abstract Test 72
- [ ] Abstract Test 73
- [ ] Abstract Test 74
- [ ] Abstract Test 75
- [ ] Abstract Test 76
- [ ] Abstract Test 77
- [ ] Abstract Test 78
- [ ] Abstract Test 79

**A.8.  Conformance Class Callback**

- [ ] Abstract Test 80

**A.9.  Conformance Class Dismiss**

- [ ] Abstract Test 81
- [ ] Abstract Test 82

**Comment by dstenger** [comment]
All mandatory tests are implemented.
