### ISSUE TITLE
status code error owing to unsupported async

### ISSUE THREAD

**Issue by pcdion** [opengeospatial/ets-ogcapi-processes10#10]
The jobControlOptions of our the echo process do not list async capability and 200 is a valid status code if the server supports sync. However, the ogcapi-processes-1.0 test returns an error with "Got unexpected status code: 200" as the reason given for several tests. 

e.g. test Job Creation Success Async

**Comment by dstenger** [comment]
Thank you for reporting. We will do further investigation.
Is there a test service available we can use to reproduce the behavior?

**Comment by jerstlouis** [comment]
@dstenger not at the moment, sorry.
This experimental version of our GNOSIS Map Server has not yet been integrated into our deployed software.

**Comment by bpross-52n** [comment]
We discussed this last Monday in the OGC API - Processes SWG. It is correct, that a HTTP status code 200 is a valid response if the server supports synchronous execution. I will update the ets.
