### ISSUE TITLE
Test Job Creation Input Ref is mistaken

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ets-ogcapi-processes10#13]
The test for `/req/core/job-creation-input-ref` seems to be confused based on its explanation saying _No input with href detected_.
This abstract test points to a non-existing requirement, which was probably merged into requirement 18.

All processes need to always support an input by reference, as per requirement 18 B (`/req/core/process-execute-inputs`).

A proper test would test submitting input by reference for possible input types.

See also [#285](https://github.com/opengeospatial/ogcapi-processes/issues/285).

**Comment by dstenger** [comment]
Thank you for reporting.
We will do further investigation.
