### ISSUE TITLE
Implement recognition of the MIME type from RFC 7807

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-ogcapi-processes10#14]
The Testbed-17 CITE thread reported that the ETS does not seem to recognize the content type `application/problem+json` as a valid content type for an exception response. [Recommendation 3](https://docs.ogc.org/is/18-062r2/18-062r2.html#rec_core_problem-details) of the _OGC API - Processes_ specification, however, cites [RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807) where it specifies this as the correct MIME type for error report.

**Comment by bpross-52n** [comment]
In the CITE meeting from September 21st 2023 we discussed that we will enhance the test suite to handle the content type `application/problem+json`.
