### ISSUE TITLE
Update relation types to match those in the Standard

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-ogcapi-processes10#15]
This is from the Testbed-17 CITE ER:

A number of the tests that fail seem to be a cascaded effect of the fact that the TestNG-based ETS does not recognize the specification relation types.  For example, the test "landing Page Validation" fails because the ETS is looking for a link with relation "processes" but the correct link relation according to the specification is "http://www.opengis.net/def/rel/ogc/1.0/processes". The ETS should be modified to address this.

**Comment by gfenoy** [comment]
Please review the following method definition: https://github.com/opengeospatial/ets-ogcapi-processes10/blob/master/src/main/java/org/opengis/cite/ogcapiprocesses10/landingpage/LandingPage.java#L76

The ETS seems to be inline with the specification at this level. I would be favorable to close this issue.
