### ISSUE TITLE
cannot run docker container

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ets-ogcapi-processes10#24]
**Describe the bug**
When trying to run the docker container locally as per the [README](https://github.com/opengeospatial/ets-ogcapi-processes10#2-minutes-method), the following issues are encountered:

**To Reproduce**
```bash
mkdir CITE
cd CITE
git clone https://github.com/opengeospatial/teamengine src
git clone https://github.com/opengeospatial/ets-common.git src1
cd src1
git clone -b testbed17 https://github.com/GeoLabs/ets-ogcapi-processes10.git
cd ..
# Build the docker image
docker build . -t teamengine/ogcapi-processes:latest
[+] Building 0.1s (1/2)                                                                                                                                                                                     
 => [internal] load build definition from Dockerfile                                                                                                                                                   0.0s
 => => transferring dockerfile: 2B                                                                                                                                                                     0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount538289897/Dockerfile: no such file or directory
```

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by tomkralidis** [comment]
Thanks.  Rather than building locally, is the image on DockerHub (https://hub.docker.com/r/ogccite/ets-ogcapi-processes10) up to date (thus running with `docker run -p 8081:8080 ogccite/ets-ogcapi-processes10`)?

**Comment by dstenger** [comment]
No, Docker Hub just contains the latest release (0.2 in this case) which is one month old. Currently, this is the same status as the master branch. However, as soon as there will be new content on master branch, it will not be moved to Docker Hub automatically.

**Comment by gfenoy** [comment]
In case you replace the command below:

> ```shell
> git clone -b testbed17 https://github.com/GeoLabs/ets-ogcapi-processes10.git
> ```


With the following one:

```shell
git clone https://github.com/opengeospatial/ets-ogcapi-processes10.git
```

The procedure should work. Can you please confirm?

**Comment by tomkralidis** [comment]
Still does not work.

**Comment by tomkralidis** [comment]
Thanks @gfenoy, the following worked:

`docker build -f src1/ets-ogcapi-processes10/Dockerfile . -t teamengine/ogcapi-processes:latest`

So +1 to update the README.
