### ISSUE TITLE
Improve message reported about failures of required fields

### ISSUE THREAD

**Issue by fmigneault** [opengeospatial/ets-ogcapi-processes10#30]
**Is your feature request related to a problem? Please describe.**

When one or more required fields are flagged as below: 

![image](https://user-images.githubusercontent.com/19194484/193148026-e4e4a258-e9b8-4b62-9a8f-17436b923f5c.png)

The test should be clearer regarding why the operation failed.
In this case, the evaluated instance did have both the `id` and `version` fields in its response, but `version` happened to be defined as `null` rather than an appropriate version string. The message was therefore misleading in this case. 

**Describe the solution you'd like**
The message should make it clear why a given field fails a test. 
Details about if the field is completely missing, or of invalid type, invalid pattern/format, or other reasons (?) should be added.

**Comment by dstenger** [comment]
Thank you for reporting.
We will do further investigation.

**Comment by jerstlouis** [comment]
@fmigneault @dstenger @pcdion We run into the same issue with our implementation.

```
body: Field 'id' is required. (code: 1026)
From: body.<allOf>.<processSummary.yaml>.<allOf>.<required>
body: Field 'version' is required. (code: 1026)
From: body.<allOf>.<processSummary.yaml>.<allOf>.<required>
```

In our case, all of our processes have `version` and `id` and they are both strings, e.g. `"1.0.0"`.

**Comment by bpross-52n** [comment]
@fmigneault @jerstlouis I cannot reproduce this issue. I think this may have been fixed in the meantime. Could you test this again with the current version of the test suite?

**Comment by dstenger** [comment]
@fmigneault @jerstlouis We will close this PR on the 15th of February if there is no objection.

**Comment by fmigneault** [comment]
No objection. If the problem is encountered again, I will comment to reopen as necessary.
