### ISSUE TITLE
Update 2-minute method

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ets-ogcapi-processes10#33]
**Describe the bug**
The 2-minute method in README does not work.
It uses an the outdated Testbed 17 repository from GeoLabs rather than master, and does not copy the Dockerfile expected within the CITE directory.

**Fix**
The following works:

```sh
mkdir CITE
cd CITE
git clone https://github.com/opengeospatial/teamengine src
git clone https://github.com/opengeospatial/ets-common.git src1
cd src1
git clone https://github.com/opengeospatial/ets-ogcapi-processes10.git
cd ..
# Build the docker image
docker build -f src1/ets-ogcapi-processes10/Dockerfile . -t teamengine/ogcapi-processes:latest
# Run the docker container
docker run -d --name cite-teamengine -p 8080:8080 teamengine/ogcapi-processes:latest
```

**Comment by gfenoy** [comment]
I made the following proposal before #25.

**Comment by jerstlouis** [comment]
Thanks @gfenoy 

@ghobona Regarding #24 / #25, the 2-minutes method in the README still needs to be updated .

I don't have `mvn` installed, is that a better way to build the docker images to install mvn on the host? Thank you.
