### ISSUE TITLE
Failure on lack of mixed type

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ets-ogcapi-processes10#53]
**Describe the bug**
The ETS gives a failure on lack of mixed type in echo process for _OGC Process Description_ conformance class.

**Expected behavior**
This should be a _skip_, not a _fail_.
There is no requirement for _Processes_ implementations to have mixed type inputs.

**Additional context**
`No Input definition of 'echo' process identifies a Mixed Type input expected [true] but found [false]`

**Comment by tomkralidis** [comment]
Coming over from #69, looking for similar clarification (pygeoapi compliance).

**Comment by bpross-52n** [comment]
@jerstlouis You are right, there is no requirement that demands mixed types in process descriptions. I have created a pull request that changes from failing to skipping the test, see #73.
