### ISSUE TITLE
Confusing _More than 1 schema is valid_ errors

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ets-ogcapi-processes10#54]
**Describe the bug**
The ETS reports the following error:

```
java.lang.AssertionError: body: More than 1 schema is valid. (code: 1023)
From: body.<oneOf> expected [true] but found [false]
```

on tests _Job Creation Input Ref_ and test _Job Creation Input Validation_.

**To Reproduce**
Run latest te2 against https://maps.gnosis.earth/ogcapi

**Expected behavior**
No error or more comprehensible error report.

**Additional Context**

This seems to originate from this execution request:
```json
{
	"id": "echo",
	"inputs": {
		"stringInput": "teststring",
		"measureInput": { "value": "teststring" },
		"dateInput": "teststring",
		"imagesInput": "teststring"
	},
	"outputs": {
		"stringOutput": { "transmissionMode": "value" },
		"measureOutput": { "transmissionMode": "value" },
		"dateOutput": { "transmissionMode": "value" },
		"doubleOutput": { "transmissionMode": "value" },
		"arrayOutput": { "transmissionMode": "value" },
		"complexObjectOutput": { "transmissionMode": "value" },
		"boundingBoxOutput": { "transmissionMode": "value" },
		"imagesOutput": { "transmissionMode": "value" }
	}
}
```
when returning for this a single string value:
```json
"teststring"
```

In this case it was because only "stringOutput" was being set, and the ETS expected multiple outputs while only one was being returned.

**Comment by dstenger** [comment]
Decision during meeting 2023-08-23:
* An issue in issue tracker of the spec shall be created.
* Test suite is made more lax.
