### ISSUE TITLE
testJobCreationInputRef: is the content type correct?

### ISSUE THREAD

**Issue by pcampanella** [opengeospatial/ets-ogcapi-processes10#62]
Dear Developers,
     looking at testJobCreationInputRef I receive an error like this:
java.lang.AssertionError: Content type '/*' is not allowed for body content. (code: 203) expected [true] but found [false]

Looking the code (org/opengis/cite/ogcapiprocesses10/jobs/Jobs.java) we notice this snippet:
Response response = new DefaultResponse.Builder(httpResponse.getStatusLine().getStatusCode()).body(body).header(CONTENT_TYPE, "/*")
					.build();
Maybe there is an error in the "/*" string?
Thanks

**Comment by fmigneault** [comment]
I also received this same error on multiple job creation tests. 
I would expect valid content-types to be either `*/*` or `application/json` (given how predominant it is used in the spec), but `/` or `/*` seem invalid values.

**Comment by bpross-52n** [comment]
@pcampanella @fmigneault Can you maybe provide an URL of a test instance, so we could reproduce this behaviour?

**Comment by bpross-52n** [comment]
The content type `/*` is defined in the schemas: https://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/responses/ExecuteSync.yaml
We will discuss in the Standards Working Group whether this need to be changed. Otherwise, we will have to modify the tests.
