### ISSUE TITLE
test session results not properly displaying URL 

### ISSUE THREAD

**Issue by pcdion** [opengeospatial/ets-ogcapi-processes10#9]
In Test Session Results, among the failed tests for ogcapi-processes-1.0, the Test Requests section frequently will simply display '?' as the URL, for the GET method.

For instance, test Job Results Async Document will yield:

```
Method: | GET
URL: | ?
Outputs: | ?1<cnt:rest></cnt:rest> | 1 | <cnt:rest></cnt:rest>
1 | <cnt:rest></cnt:rest>
```

**Comment by dstenger** [comment]
Thank you for reporting. We will do further investigation.
Is there a test service available we can use to reproduce the behavior?

**Comment by jerstlouis** [comment]
@dstenger not at the moment, sorry.
This experimental version of our GNOSIS Map Server has not yet been integrated into our deployed software.
